# Makfile or packages.json
# "scripts": {
#     ...,
#     "build:css": "npx tailwindcss -i ./src/ ..." # add this
#   },
run:
	npm run start

.PHONY: tailwind
tailwind:
	npx tailwindcss -i ./src/styles/globals.css -o ./public/output.css  --watch
