[tool.black]
line-length = 100

[tool.isort]
profile = "black"

[tool.pytest.ini_options]
testpaths = ["tests"]
python_files = ["test*.py"]
python_classes = ["Test"]
python_functions = ["test"]

[tool.coverage.report]
omit = [
  "*/tests/*",
  "*/migrations/*",
  "*/__init__.py",
  ".venv/*",
  "*/apps.py",
  "config/asgi.py",
  "config/wsgi.py",
  "manage.py",
]
